### ISSUE TITLE
Warning: Failed prop type: Invalid prop `locale` of type `string` supplied to `MonthSelectorCalendar`, expected `object`.

### ISSUE THREAD

**Issue by jurajkrivda** [vinodkumar8/react-native-month-selector#6]

**Comment by isaaclem** [comment]
@jurajkrivda It's due to locale in defaultProps is string type but propTypes for locale is object. I've raised a PR for that quite some time ago but still pending to be merged

**Comment by vinodkumar8** [comment]
This is fixed now and will close this
