### ISSUE TITLE
The calender selecting a month doesnot working!?...

### ISSUE THREAD

**Issue by vishnujith08** [vinodkumar8/react-native-month-selector#9]
if we select a month the selection part doesn't work.if there any solution please support me.

**Comment by vinodkumar8** [comment]
can you paste your code @vishnujith08

**Comment by maiconkf** [comment]
> can you paste your code @vishnujith08

`<MonthSelectorCalendar selectedDate={this.state.month} monthTapped={ console.log('date') } containerStyle={{width: '100%'}} />`

**Comment by Subway19** [comment]
@vinodkumar8  `monthTapped` method is not getting invoked. I recently updated react native to `0.59.10` and this error is occurring. I am using `1.4.0` of this module. Please resolve.

**Comment by jibraniqbal666** [comment]
use onMonthTapped instead monthTapped

**Comment by vinodkumar8** [comment]
@Subway19  please let me know if it works as per @jibraniqbal666  suggestions

**Comment by Subway19** [comment]
@vinodkumar8  Yes, i saw the documentation and the method has changed. @jibraniqbal666  suggestion works. @vinodkumar8  you can close this
